#!/bin/bash

if [[ $1 == "start" ]]; then
  [[ "$(docker compose ps | grep keycloak_web | wc -l)" -gt "0" ]] && docker compose down
  docker compose up -d && echo -e "\r\n ✔ Veuillez patienter quelques secondes ..." && sleep 10 && echo -e "\r\n ✔ KEYCLOAK dispo sur http://localhost:8080\r\n"
elif [[ $1 == "status" ]]; then
  docker compose ps
elif [[ $1 == "stop" ]]; then
  [[ "$(docker compose ps | grep keycloak_web | wc -l)" -gt "0" ]] && docker compose down || echo " - Pas de container lancé !!!"
else
  echo 'Commande incorrect. Un argument autorisé: status stop ou start'
fi
